#!/usr/bin/env python3
"""Convert C lang_specs.c initializer tables to Rust static tables.

Parses the C source (arrays of node-type strings + the designated-initializer
spec table) and emits Rust `LanguageSpec` rows. The ts_factory symbol maps to
the crates.io tree-sitter grammar crate name for later wiring.
"""
import re, sys

SRC = 'internal/cbm/lang_specs.c'
OUT = 'internal/cbm/src/lang_specs.rs'

text = open(SRC).read()

# ── 1. Collect named string arrays ─────────────────────────────
# static const char *name[] = { "a", "b", NULL };
arrays = {}
for m in re.finditer(r'static const char \*(\w+)\[\]\s*=\s*\{(.*?)\};', text, re.S):
    name, body = m.group(1), m.group(2)
    items = re.findall(r'"([^"]*)"', body)
    arrays[name] = items

# ── 2. Embedded spec arrays ────────────────────────────────────
embedded = {}
for m in re.finditer(r'static const CBMEmbeddedLangSpec (\w+)\[\]\s*=\s*\{(.*?)\};', text, re.S):
    name, body = m.group(1), m.group(2)
    entries = []
    for em in re.finditer(r'\{"([^"]*)",\s*"([^"]*)",\s*CBM_LANG_(\w+)\}', body):
        entries.append((em.group(1), em.group(2), em.group(3)))
    embedded[name] = entries

# ── 3. Parse the spec table rows ───────────────────────────────
table_start = text.index('static const CBMLangSpec lang_specs[CBM_LANG_COUNT] = {')
table = text[table_start:]
# Split on designated initializer heads: [CBM_LANG_X] = { ... }
row_re = re.compile(r'\[CBM_LANG_(\w+)\]\s*=\s*\{')
heads = list(row_re.finditer(table))
rows = {}
for i, m in enumerate(heads):
    lang = m.group(1)
    start = m.end()
    # find matching close brace: braces nest only via inline arrays
    depth = 1
    j = start
    while depth > 0 and j < len(table):
        if table[j] == '{':
            depth += 1
        elif table[j] == '}':
            depth -= 1
        j += 1
    body = table[start:j-1]
    rows[lang] = body

# Field order in CBMLangSpec:
FIELDS = [
    'language', 'function_node_types', 'class_node_types', 'field_node_types',
    'module_node_types', 'call_node_types', 'import_node_types',
    'import_from_types', 'branching_node_types', 'variable_node_types',
    'assignment_node_types', 'throw_node_types', 'throws_clause_field',
    'decorator_node_types', 'env_access_functions', 'env_access_member_patterns',
    'ts_factory', 'embedded_imports',
]

def split_fields(body):
    """Split top-level commas, keeping inline {...} arrays intact."""
    parts, depth, cur, i = [], 0, '', 0
    while i < len(body):
        c = body[i]
        if c == '{':
            depth += 1
        elif c == '}':
            depth -= 1
        if c == ',' and depth == 0:
            parts.append(cur.strip())
            cur = ''
            i += 1
            continue
        cur += c
        i += 1
    if cur.strip():
        parts.append(cur.strip())
    return parts

def resolve_value(v):
    """C value expression → Rust expression for one field."""
    v = v.strip()
    if v == 'NULL':
        return 'None'
    # The row's first field repeats the language name (CBM_LANG_X) — skip it.
    if v.startswith('CBM_LANG_'):
        return 'SKIP'
    # Inline compound literal: (const char *[]){...} or bare {...}
    if v.startswith('{') or v.startswith('(const char'):
        items = re.findall(r'"([^"]*)"', v)
        return f'some(&{items!r})'.replace("'", '"')
    if v.startswith('"'):
        return f'Some({v})'
    if v in arrays:
        items = arrays[v]
        return f'some(&{items!r})'.replace("'", '"')
    if v in embedded:
        entries = embedded[v]
        if not entries:
            return 'Some(&[])'
        parts = ', '.join(
            f'EmbeddedLangSpec {{ script_node_type: "{s}", content_node_type: "{c}", embedded_language: Language::{l} }}'
            for s, c, l in entries)
        return f'Some(&[{parts}])'
    if v.startswith('tree_sitter_'):
        return None  # handled separately
    raise ValueError(f'unresolved symbol: {v!r}')

# tree-sitter factory symbol → crate name (crates.io equivalents)
def factory_crate(sym):
    crate = sym.replace('tree_sitter_', '')
    special = {
        'c_sharp': 'c-sharp', 'php_only': 'php', 'COBOL': 'cobol',
        'typescript': 'typescript', 'tsx': 'tsx',
    }
    return special.get(crate, crate)

# ── 4. Emit Rust ───────────────────────────────────────────────
out = []
out.append('''//! lang_specs.rs — 1:1 rewrite of `internal/cbm/lang_specs.{c,h}`.
//!
//! Generated by tools/gen_lang_specs.py from the C tables — regenerate
//! after editing the C source (until the C source is deleted at the end of
//! this layer's rewrite). Node-type arrays and embedded-sublanguage specs
//! are verbatim; `ts_factory` resolves through the tree-sitter crate map.

use crate::Language;

/// A sub-language embedded in a host AST (C CBMEmbeddedLangSpec): the host
/// grammar leaves `content_node_type` unparsed; it is re-parsed with the
/// embedded grammar so extractors run on the inner AST.
#[derive(Debug, Clone, Copy)]
pub struct EmbeddedLangSpec {
    pub script_node_type: &'static str,
    pub content_node_type: &'static str,
    pub embedded_language: Language,
}

/// Per-language grammar knowledge (C CBMLangSpec).
#[derive(Debug, Clone, Copy)]
pub struct LanguageSpec {
    pub language: Language,
    pub function_node_types: &'static [&'static str],
    pub class_node_types: &'static [&'static str],
    pub field_node_types: &'static [&'static str],
    pub module_node_types: &'static [&'static str],
    pub call_node_types: &'static [&'static str],
    pub import_node_types: &'static [&'static str],
    pub import_from_types: &'static [&'static str],
    pub branching_node_types: &'static [&'static str],
    pub variable_node_types: &'static [&'static str],
    pub assignment_node_types: &'static [&'static str],
    pub throw_node_types: &'static [&'static str],
    pub throws_clause_field: Option<&'static str>,
    pub decorator_node_types: &'static [&'static str],
    pub env_access_functions: &'static [&'static str],
    pub env_access_member_patterns: &'static [&'static str],
    /// crates.io tree-sitter grammar crate name (C: TSLanguage factory).
    pub ts_crate: Option<&'static str>,
    pub embedded_imports: &'static [EmbeddedLangSpec],
}

pub fn some(v: &'static [&'static str]) -> Option<&'static [&'static str]> {
    if v.is_empty() {
        None
    } else {
        Some(v)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Language {
    _Never,
}
''')
# placeholder types end; real table below
out = []  # restart — the header above had a placeholder; final file below

header = '''//! lang_specs.rs — 1:1 rewrite of `internal/cbm/lang_specs.{c,h}`.
//!
//! Generated by tools/gen_lang_specs.py from the C tables — regenerate
//! after editing the C source (until the C source is deleted at the end of
//! this layer's rewrite). Node-type arrays and embedded-sublanguage specs
//! are verbatim; `ts_factory` resolves through the tree-sitter crate map.

use crate::Language;

/// A sub-language embedded in a host AST (C CBMEmbeddedLangSpec): the host
/// grammar leaves `content_node_type` unparsed; it is re-parsed with the
/// embedded grammar so extractors run on the inner AST.
#[derive(Debug, Clone, Copy)]
pub struct EmbeddedLangSpec {
    pub script_node_type: &'static str,
    pub content_node_type: &'static str,
    pub embedded_language: Language,
}

/// Per-language grammar knowledge (C CBMLangSpec).
#[derive(Debug, Clone, Copy)]
pub struct LanguageSpec {
    pub language: Language,
    pub function_node_types: &'static [&'static str],
    pub class_node_types: &'static [&'static str],
    pub field_node_types: &'static [&'static str],
    pub module_node_types: &'static [&'static str],
    pub call_node_types: &'static [&'static str],
    pub import_node_types: &'static [&'static str],
    pub import_from_types: &'static [&'static str],
    pub branching_node_types: &'static [&'static str],
    pub variable_node_types: &'static [&'static str],
    pub assignment_node_types: &'static [&'static str],
    pub throw_node_types: &'static [&'static str],
    pub throws_clause_field: Option<&'static str>,
    pub decorator_node_types: &'static [&'static str],
    pub env_access_functions: &'static [&'static str],
    pub env_access_member_patterns: &'static [&'static str],
    /// crates.io tree-sitter grammar crate name (C: TSLanguage factory).
    pub ts_crate: Option<&'static str>,
    pub embedded_imports: &'static [EmbeddedLangSpec],
}

pub const EMPTY: &[&str] = &[];
'''
out.append(header)

rows_src = []
unresolved = []
for lang, body in rows.items():
    if lang == 'COUNT':
        continue
    parts = split_fields(body)
    if len(parts) != len(FIELDS):
        unresolved.append((lang, 'field count', len(parts)))
        continue
    vals = {}
    ts_sym = None
    for f, v in zip(FIELDS, parts):
        if f == 'language':
            continue  # first field repeats CBM_LANG_X
        if f == 'ts_factory':
            if v.startswith('tree_sitter_'):
                ts_sym = v
            continue
        if f == 'embedded_imports':
            r = resolve_value(v)
            vals[f] = r if r is not None else 'Some(&[])'
            continue
        try:
            vals[f] = resolve_value(v)
        except ValueError as e:
            unresolved.append((lang, str(e), v[:60]))
            vals[f] = 'some(EMPTY)'
    if ts_sym is None:
        unresolved.append((lang, 'no ts_factory', ''))
        continue
    rows_src.append((lang, vals, factory_crate(ts_sym)))

# Emit constants for arrays + the table function.
arr_consts = {}
counter = 0
def const_for(expr):
    global counter
    counter += 1
    return f'A{counter}'

# Instead of consts, inline the arrays directly in the table for simplicity.
enum_order = [l.strip().replace('CBM_LANG_','',1) for l in open('/tmp/enum_final.txt') if l.strip()]
by_lang = {lang: (vals, crate) for lang, vals, crate in rows_src}
table_lines = ['/// All language specs, indexed by `Language as usize`.',
               'pub static SPECS: [LanguageSpec; crate::LANG_COUNT as usize] = [']
for lang in enum_order:
    if lang not in by_lang:
        # C zero-initializes missing rows: no node types, no factory.
        table_lines.append('    LanguageSpec {')
        table_lines.append(f'        language: Language::{lang},')
        for f in ['function_node_types','class_node_types','field_node_types','module_node_types',
                  'call_node_types','import_node_types','import_from_types','branching_node_types',
                  'variable_node_types','assignment_node_types','throw_node_types']:
            table_lines.append(f'        {f}: EMPTY,')
        table_lines.append('        throws_clause_field: None,')
        table_lines.append('        decorator_node_types: EMPTY,')
        table_lines.append('        env_access_functions: EMPTY,')
        table_lines.append('        env_access_member_patterns: EMPTY,')
        table_lines.append('        ts_crate: None,')
        table_lines.append('        embedded_imports: &[],')
        table_lines.append('    },')
        continue
    vals, crate = by_lang[lang]
    def g(k, dflt='EMPTY'):
        r = vals.get(k, dflt)
        if r in ('None', 'some(EMPTY)', 'Some(&[])'):
            return 'EMPTY'
        if r.startswith('some(&') and r.endswith(')'):
            return r[5:-1]  # some(&[...]) -> &[...]
        if r.startswith('Some(&') and r.endswith('])') and '"' not in r.split('[',1)[0]:
            # Some(&[("a","b",LANG)]) style stays (embedded) — pass through
            return r
        return r
    embedded_expr = vals.get('embedded_imports', 'Some(&[])')
    if embedded_expr in ('None', 'Some(&[])'):
        embedded_expr = '&[]'
    elif embedded_expr.startswith('Some(&') and embedded_expr.endswith('])'):
        embedded_expr = embedded_expr[5:-1]  # Some(&[...]) -> &[...]
    table_lines.append(f'    LanguageSpec {{')
    table_lines.append(f'        language: Language::{lang},')
    for f in ['function_node_types','class_node_types','field_node_types','module_node_types',
              'call_node_types','import_node_types','import_from_types','branching_node_types',
              'variable_node_types','assignment_node_types','throw_node_types']:
        table_lines.append(f'        {f}: {g(f)},')
    tv = vals.get('throws_clause_field', 'None')
    table_lines.append(f"        throws_clause_field: {tv},")
    table_lines.append(f"        decorator_node_types: {g('decorator_node_types')},")
    table_lines.append(f"        env_access_functions: {g('env_access_functions')},")
    table_lines.append(f"        env_access_member_patterns: {g('env_access_member_patterns')},")
    table_lines.append(f'        ts_crate: Some("{crate}"),')
    table_lines.append(f'        embedded_imports: {embedded_expr},')
    table_lines.append('    },')
table_lines.append('];')
out.extend(table_lines)

out.append('''
/// Get the spec for a language (C cbm_lang_spec).
pub fn lang_spec(lang: Language) -> &'static LanguageSpec {
    &SPECS[lang as usize]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_language_has_a_spec() {
        for l in Language::ALL {
            let spec = lang_spec(l);
            assert_eq!(spec.language, l);
        }
    }

    #[test]
    fn embedded_specs_parse() {
        // Vue/Svelte/HTML/Astro embed JavaScript; Astro's frontmatter is TS.
        for lang in [Language::VUE, Language::SVELTE, Language::HTML] {
            let spec = lang_spec(lang);
            let e = spec.embedded_imports;
            assert!(!e.is_empty(), "{lang:?}");
            assert_eq!(e[0].content_node_type, "raw_text");
        }
        let astro = lang_spec(Language::ASTRO);
        assert_eq!(astro.embedded_imports[0].embedded_language, Language::TYPESCRIPT);
    }

    #[test]
    fn count_matches_c_table() {
        // The C table has a row per language; rows without a body are
        // zero-initialized. Verify a known populated and a known empty row.
        assert!(lang_spec(Language::GO).ts_crate.is_some());
    }

    #[test]
    fn go_and_python_rows() {
        let go = lang_spec(Language::GO);
        assert!(go.function_node_types.contains(&"function_declaration"));
        assert_eq!(go.ts_crate, Some("go"));
        let py = lang_spec(Language::PYTHON);
        assert!(py.call_node_types.contains(&"call"));
        assert!(py.function_node_types.contains(&"function_definition"));
        assert_eq!(py.ts_crate, Some("python"));
    }
}
''')

open(OUT, 'w').write('\n'.join(out))
print(f'rows: {len(rows_src)}, unresolved: {len(unresolved)}')
for u in unresolved[:20]:
    print('  UNRESOLVED:', u)
